num1=int(input("Enter First number:"))
num2=int(input("Enter Second number:"))
print("both numbers are equal: ", num1==num2)
print("num1 is less than num2: ",num1<num2)
print("num1 is greater than num2: ",num1>num2)
